### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#1]
![test](https://cloud.githubusercontent.com/assets/10883357/11019343/3c947da0-85fe-11e5-9355-3e3b6c8f8cde.png)
test
test
test

**Comment by Kraxeeer** [comment]
I can't open  so...
I have some issuses:
Can't join servers (connect ip:port)
Can't use some commands (some? Many... Buy/ and muuuuuch more comands not working
 Error "Uncown Comand"
Can't use C4
Binds are working but anyway if i: bind "9" "buy" i got "uncown comand" in console. I have binded console to 0 key.
Touch controll work good.
I have CS 1.6 v48 Steam clean version files in sdcard/xash/ (so here are valve and cstrike folders) and your latest port zip (~10 hours ago). 
I want to fix buy menu. Any chance?

**Comment by Kraxeeer** [comment]
Nice but... Playing without vgui is fu**ed up... I can't buy guns

**Comment by a1batross** [comment]
@Kraxeeer just type "buy" in a console.
It in a beta test now.
