### ISSUE TITLE
При убийстве игроков

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#10]
1. Перепутан цвет в статусе в верху справа при убийстве... террористы показаны синим а не красным, менты наоборот

2. Должен еще тамже отображаться значек оружия из которого было убийство или черепок - если убили в голову... сейчас череп показывается.

3. Не пишется из какого оружия убил.. написано в верху с лева Name killed  witch  by (должно быть название оружия)

**Comment by a1batross** [comment]
1. Исправлено в 4a48086789de556f0da45ec87e9cb505d3d292ab

2. 3. 4a48086789de556f0da45ec87e9cb505d3d292ab
