### ISSUE TITLE
Возможно глупый вопрос, но с ReGameDLL_CS взаимодействуете ?

### ISSUE THREAD

**Issue by underworlddemon** [SDLash3D/cs16-client#100]
Возможно глупый вопрос, но с ReGameDLL_CS взаимодействуете ?
https://github.com/s1lentq/ReGameDLL_CS/

**Comment by lewa-j** [comment]
Уже портировали.

**Comment by a1batross** [comment]
Да, его портировали уже. Но для этого пришлось форкнуть в отдельный проект без bloatware, типа привязки к Steam. 
Ну и плюс Xash3D-зависимые фиксы, которые всё равно не примут в мейнстрим.

Но его только портировали, cs16-client использует SDK от китайского cs16nd. Что первее нашлось. Да и адаптировать его проще было.
