### ISSUE TITLE
SCOREBOARD - неправильное отображение графы Spectators

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#104]
Данные Spectators и разделитель отображаются, когда нет спектаторов. + блок всегда должен быть в низу скоррборда. Он может быть вверху или посередине. 
![screenshot_2016-02-17-01-03-06](https://cloud.githubusercontent.com/assets/5286127/13105477/246ad0d6-d585-11e5-8696-1c5ad6bdc29d.jpg)
![screenshot_2016-02-16-20-08-06](https://cloud.githubusercontent.com/assets/5286127/13105478/246c4e20-d585-11e5-9ce4-4bf6e436f263.jpg)

**Comment by a1batross** [comment]
Надо вовсе убрать автоматическую сортировку. Это пришло ещё из HL1. 
В CS же всегда порядок жёсткий -- CT->T->Все остальные как спектаторы.

Тогда можно очень хорошо облегчить код скорборда.
