### ISSUE TITLE
PLAYER - застревание друг в друге и в геометрии карты. 

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#105]
Во время игры игроки могут застрять друг в друге, иногда спасает прыжок. Чтобы выпрыгнуть из игрока. Аналогично, при приседании можно по колено провалиться в пол. Возможная причина ПЕРДИКТА. ;)

**Comment by Zu1iNMage** [comment]
Друг в друге игроки застревают и на глдсрс, поэтому на серва ставят плагин на то что б тиммейты спокойно проходили сквозь друг друга

**Comment by sergiopoverony** [comment]
Проверено в стиме. Застревания игроков в стиме нет. Есть только "Блокировка" когда игрок не пропускает другого. В данном баге описывалось то, что из за предикта, один игрок застревает внтутри другого, аналогично как и в землю проваливается. Из другого игрока еще можно вылезти нажимая прыжок, из земли вылезти невозможно.

**Comment by a1batross** [comment]
Такое и в хл1 иногда происходит. 

Но предикт тут не виноват. Даже если предикт СОВЕРШИЛ ОШИБКУ, то оно затрется вместе со следующим пакетом от сервера.
