### ISSUE TITLE
ПОИСК СЕРВЕРОВ

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#106]
Поиск серверов не понятно как работает, может быть так как на картинке (2 раза 1 сервер)+ бывает не туда подключается.
![screenshot_2016-02-19-11-56-53](https://cloud.githubusercontent.com/assets/5286127/13171574/561801ee-d715-11e5-81c8-38a69e0a654b.jpg)

**Comment by mittorn** [comment]
клиент тут причём? это старый баг меню, который никто не хочет править.
