### ISSUE TITLE
МОДЕЛЬ ИГРОКА - неправильная модель игрока

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#107]
Захожу за террористов, моя модель у всех отображается как мент "gign"/
Перезаходил несколько раз - повторяется. Поглядел userconfig в который я прописывал команды 
А там у меня, чтобы избавиться от сральни в лог по поводу отсутсвия анимация... стоит такого вида заглушка **set model "some_name"** 
Вывод: Модель игрока можно подменять (1-е), ну а на второе, в консоль срет на отсутсвие секвенции анимаций модели gordon, так как подефолту указана она.

**Comment by a1batross** [comment]
А может КС ее специально ставит? :)
