### ISSUE TITLE
Чит команды

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#11]
Нужно отключить возможность noclip, god и прочих чит кодов. (в КС на клиенте они вообще никогда не работали)

**Comment by a1batross** [comment]
Они на сервере специально подключены.

**Comment by sergiopoverony** [comment]
В КС они не работают даже если  на сервере включено

**Comment by mittorn** [comment]
Это движок их запрещает.
В любом случае, без sv_cheats всё нормально

**Comment by a1batross** [comment]
Ну и тем более, что ГС на лету не умеет читы включать.
