### ISSUE TITLE
RADIO повторное срабатывание командами slot1 после menuselect 1.

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#113]
Срабатывание команд радио по slot1... после menuselect 1...
Необходимо либо переписывать меню и писать slot'ы вместо menuselect, либо запретить выполнение радио команд слотами после menuselect

**Comment by a1batross** [comment]
Это фича ХЛ и КС. Чтобы на цифры на клаве биндились на слоты и меню.

Не баг, короче.

**Comment by ahsim** [comment]
ну может и не баг, тогда переделывать мне я так понял? вместо menuselect 1 вставлять slot1 в менюшках?
Сейчас получается вызвал радио, выбрал группу радио комманд, нажал - команда проговорилась, далее жмеш на кнопку переключения на нож (кнопка с командой slot3) - срабатывает еще одна радио команда из той же группы но под номером 3

**Comment by a1batross** [comment]
Можно и слот использовать, просто он работает через тот же menuselect. Если это исправит такое поведение, тогда отлично.

Я бы вообще рекомендовал использовать цифры, потому что с ними точно никогда и ничего не случится. А тачевое хз, может сработать и может так же не сработать. 

Такое было на предыдущих билдах? Вдруг я чего сломал(хотя каюсь, меню не трогал вообще)

**Comment by ahsim** [comment]
исправил менюшку
