### ISSUE TITLE
OVERVIEW - имя игрока в центре карты

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#119]
При смерти, когда видно нарисованную карту. Имя игрока за которым следишь - отображается на маркере и по центру карты. При условии что имена игроков по центру... хотя вообще это не должно отображаться. 
![screenshot_2016-02-25-11-58-00](https://cloud.githubusercontent.com/assets/5286127/13330361/61d09050-dc1a-11e5-90dd-fddf32d0930a.png)
![screenshot_2016-02-25-11-54-42](https://cloud.githubusercontent.com/assets/5286127/13330370/6c5b097e-dc1a-11e5-8dfe-c4e02e8a105a.png)

**Comment by a1batross** [comment]
Это не hud_centerid?

Не забывай, это чертов спектатор, который я совсем не начинал делать.

**Comment by a1batross** [comment]
Я это кстати уже пофиксил. Статусбары по правилам КС вовсе не должны рисоваться во время спектатора, что я и сделал.
