### ISSUE TITLE
СЕКВЕНЦИИ СКЕЛЕТА cstrike/models/player.mdl

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#12]
Непонятная рандомная ошибка, при перестрелке в ближнем бою. Скриншот приложил
![0001](https://cloud.githubusercontent.com/assets/5286127/11020219/8fea0330-863a-11e5-80bb-049d7588eb99.png)

**Comment by sergiopoverony** [comment]
Воспроизвел. Надо подольше поиграть. Просто потом сыпать всю консоль начинает этим

**Comment by a1batross** [comment]
Надо квар model ставить таким же, за кого ты сейчас и играешь. 
Хотя судя по всему, это вообще игра игнорит. Только один движок ругается на несоответстввие количества анимаций в модели.

**Comment by sergiopoverony** [comment]
НЕ ИСПРАВЛЕНО!

**Comment by sergiopoverony** [comment]
Алибек, с тобой обсуждали... по поводу этого. Замени как я указал .

**Comment by a1batross** [comment]
Это не так критично. Как дотянутся руки, выправлю. 
И то это полностью не выправить, пока движок смотрит в квар model.

**Comment by sergiopoverony** [comment]
Найдено решение. Нужно чтобы в конфиг прописывался model "player" вместо существующего model "gordan"
Алибек -прошу пофиксить

**Comment by a1batross** [comment]
В коде клиента model оверрайдится, но её все ещё выставлять исправлять из конфигов.
В общем, если вылазит, значит это ваш конфиг.
