### ISSUE TITLE
ОРУЖИЕ - перезарядка

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#120]
Иногда не отображается анимация перезарядки.. стреляешь - пульки кончились.. он тупо стоит, анимации нету... проходит время которое тратится на перезарядку и после этого  - можно стрелять.

**Comment by a1batross** [comment]
Да блин. Вам то убери клиентскую перезарядку, то верни обратно.

С клиентской же баг с двойной анимацией. Я знал, что придется его
исправлять

**Comment by sergiopoverony** [comment]
А кто просил убрать? Стивен только и просил. А все остальные только за то, чтобы было как в оригинале.  Кому надо убрать сделают lc_lw 0

**Comment by a1batross** [comment]
Читайте меня полностю. Особенно последние абзацы.

**Comment by sergiopoverony** [comment]
Где читать.. уже куча всего... я незнаю где читать

**Comment by a1batross** [comment]
>С клиентской же баг с двойной анимацией. Я знал, что придется его исправлять

**Comment by sergiopoverony** [comment]
А ну лавдно... ждем. а то щас вообще иногда ее нет

**Comment by a1batross** [comment]
Fixed.
