### ISSUE TITLE
SCOREBOARD - подсветка имени игрока

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#122]
После обновлений - подсветка имени игрока стала слишком яркой. 
![2vgwcsj4lz0](https://cloud.githubusercontent.com/assets/5286127/13490983/87a2d00e-e151-11e5-905b-5cf0841ff685.jpg)
Дима откомментировал как 
**. Пускай Алибек исправляет, у него там FillRGBABlend использовался, хотя он неправильно изначально работал

**Comment by a1batross** [comment]
Пофиксил.
