### ISSUE TITLE
WEAPON - XM1014 - звук при перезарядке

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#125]
Если зажать стрельбу и не отпускать, после того как кончаются патроны, начинается багнутый звук загрузки патронов... будто он высыпал кучу патронов в деревянное ведро/карыто (так звучит).

**Comment by ahsim** [comment]
замечал не только с этим оружием. Именно тот момент когда зажал и не отпускаешь, так же и с анимацией проблемы в этот момент

**Comment by a1batross** [comment]
Нашёл где проблема пряталась. Но надо то место хорошо потестировать на других играх, помимо CS.

**Comment by a1batross** [comment]
https://github.com/SDLash3D/xash3d/commit/5105d7200f2d0acfd33748a783abd3ebef426a98
