### ISSUE TITLE
CROSSHAIR - cl_crosshair_translucent

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#126]
Не работает команда cl_crosshair_translucent 
подозреваю что всё тотже FillRGBABlend

**Comment by a1batross** [comment]
Всё в порядке. На светлых поверхностях прицел белеет, ибо правила смешивания такие. 

Тут может сыграть ещё `stupid gles bug`, как я его ещё называю. Но такое исправить попросту невозможно, если не написать собственный драйвер или перейти на GLES2.
