### ISSUE TITLE
Игроки и анимации

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#13]
Нет анимации на игроках, при ходьбе-стрельбе. При установке бомбы  - анимация работает.

**Comment by a1batross** [comment]
Частично исправлено, закрывать не стану. Оружия всё равно ещё вверх повернуты.

**Comment by sergiopoverony** [comment]
Ключ анимации на нулевой. Когда модели редактирцешь - это крайнее верхнее левое положение поворота игрока.

**Comment by ahsim** [comment]
да, проблема с анимацией есть, вот что пишут тестеры:
*Эффект выстрела у друга\противника находится в животе у модельке, ну или рядом с ним.
*У глока анимка глючит, при выстреле затворка не возвращается обратно. 
*При вторичном и последующих выстрелах отсутствуют не только спрайты огня и звуки,но и анимация выстрела.
*У Глока и (возможно) Famas при очередях из 3 выстрелов анимация присутствует всегда.
*У некоторых моделей(в данном случае у P90). Приклад отсутствует(прозрачен).
*У awp нет затемнения при зуме,затем остаётся только перекрёстке прицела на всем протяжении раунда.
*У меня не отображаются некоторые модели Террористов и Контр-террористов(возможно,только у меня)
*Модель ножа дерганная,при многочисленных тапах по кнопке "огонь" анимация проигрывается заного,не заканчивая предыдущий удар.
*cl_lw 0 и другие команды(у меня- cl_righthand 1 ) не работаю при настройки в лаунчере даже если использовать команду reconnect(в commands line argument)
*За террористов не возможно взять галил. Он покупается но в руки не берётся. 4. У оружий с коллиматорным прицелом пропадает сам прицел.

**Comment by sergiopoverony** [comment]
Проблема не только у нас в клиенте/сервере для ПК - аналогичная ситуация.

**Comment by a1batross** [comment]
Анимация пофикшена с новым рендером.
