### ISSUE TITLE
запрет наблюдать за противниками после смерти

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#131]
Есть необходимость сделать возможность запретить мертвым наблюдать за противниками. Сейчас передают расположение противника через встроенный чат. Если это исправишь, то будут передавать через скайп или еще что то. Хоть и в оригинале не было такого, то, думаю, здесь лучше сделать так. Пусть не в первом релизе, но потом лучше бы сделать.

**Comment by a1batross** [comment]
И что? Что такого в том, что как-то передают местоположение? 

Пусть. В кооперации нет ничего плохого. 

Но чат от трупов я пофикшу.
