### ISSUE TITLE
спектатор гуи

### ISSUE THREAD

**Issue by Zu1iNMage** [SDLash3D/cs16-client#136]
Счетчик побед команд в спектатор гуи не соответствует тому что в наяву.
Так же напоминаю на всякий случай про артефакты вместо иконки таймера и про артефакты которые появляются вместо других пунктов в спектатор гуи.
Скорее не баг, но все же - толщина спектатор гуи слишком здоровая, его зона перекрывает слишком большой процент экрана.

**Comment by a1batross** [comment]
Это был счетчик побед? Я думал и количество оставшихся в живых игроков.

**Comment by a1batross** [comment]
Толщина большая, потому что кнопки тачевые. 

Ну и к тому же, пропорции экрана у нас далеки от почти квадратного 
4:3.

**Comment by Zu1iNMage** [comment]
Да, это счетчик побед команд

**Comment by THE-Swank** [comment]
Даже на тачевые кнопки полоски великоваты, у меня все влазит и довольно много места остается, не знаю зависит ли оно от разрешения

**Comment by a1batross** [comment]
@THE-Swank
Покажи скрин. И размер экрана реальный. В дюймах.

**Comment by THE-Swank** [comment]
http://cs631918.vk.me/v631918495/1bea5/CfC9_MmK0Qo.jpg 4 дюйма
