### ISSUE TITLE
Снайперские винтовки

### ISSUE THREAD

**Issue by Zu1iNMage** [SDLash3D/cs16-client#137]
1) На экране не должо быть прицела ни у одной снайперки (crosshair).
2) Если умереть во время прицеливания (зум), то перекрестие зума остается до тех пор, пока камера не переключится в наблюдение.
3) Если при выстреле с авп резко переключить на другое оружие (lastinv), а затем обратно на авп, то на миг появляется зум + гильза вылетает с леворукой стороны, в оригинале гильза и так вылетает запоздало после переключения, да, но вылетает с правильной стороны.

**Comment by a1batross** [comment]
1) Ок. Перечисли их. 
2) Fov такой же остаётся?
3) Может случайно оказаться, что это Brass от CZero, а он местами отличается. Потому расчеты происходят неверные и выдает гильза с другой стороны. 
С fov проверю.

**Comment by Zu1iNMage** [comment]
Фов тот же, темная обоасть зума исчезает, т.е. мы видим наш труп и нашего убийцу, но на экране остается перекрестие от зума.
На каких снайперках не должно быть крошэира - awp, scout, krieg552 commando, g3sg1.
