### ISSUE TITLE
Анимации

### ISSUE THREAD

**Issue by Zu1iNMage** [SDLash3D/cs16-client#138]
При переключении между м4а1 и дигл - анимация доставания оружия теряется
Авп и дигл - то же самое

**Comment by a1batross** [comment]
Попереключал. Воспроизвести не могу. 

Оно при каких условиях происходит?

**Comment by Zu1iNMage** [comment]
Поясни условия? Играю хоть на серве хоть в одиночке происходит такое, кл_лв на 1 как нужно стоит

**Comment by Zu1iNMage** [comment]
Разобрался, те нужно создать кнопку и повесить на нее команду "lastinv" - этой кнопкой переключай оружия
