### ISSUE TITLE
Партиклы

### ISSUE THREAD

**Issue by Zu1iNMage** [SDLash3D/cs16-client#139]
Вкурсе про отсутствие партиклмэн, но если захочешь этим заняться.
Партиклы крови в оригинале жирнее чем есть сейчас в клиенте
При попадании в голову без шлема, выпускается струя крови в соответствующую сторону, струя не преземляется на пол, а как бы исчезает при столкновении с полом или стеной.
Партиклы, что от попаданий в стену, что кровь, в зависимости от расстояния становятся больше (чем дальше тем больше у игрока на экране они выглядят, в пределах разумного). 
Если не будешь этим заниматься то просто закрой это эшью.

**Comment by a1batross** [comment]
Дело не в нем, кажется, а в разной реализации движковых партиклей, типа TE_BLOODSTREAK. 

В ближайшее время вряд ли займусь этим.
