### ISSUE TITLE
Покупка оружия

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#14]
1. У террористов 1 автомат Galil покупается, деньги отменяются, но оружие не берется в руки и не вызывается через слот

**Comment by GFOXSH** [comment]
Тестировал покупку разного оружия. Все покупается.

**Comment by a1batross** [comment]
Исправлено. У Galil позиция была на 18-ом месте, когда увеличено было по ошибке лишь до 17
