### ISSUE TITLE
Nvidia Shield Controller doesn't seem to work with cs16-client

### ISSUE THREAD

**Issue by stgarf** [SDLash3D/cs16-client#140]
I just loaded up cs16-client on my nvidia shield and cannot use the nvidia controller to navigate the CS UI.

EDIT:
~~What debugging information do you need from me?~~
Xash3D v0.17.1
CS16Client v1.0

And I just stumbled upon this, most likely my issue: SDLash3D/xash3d-android-project#54

**Comment by a1batross** [comment]
We don't have such devices for testing.

You may try using some apps, that will bind controller keys to keyboard keys. And after bind it in Xash3D itself.
