### ISSUE TITLE
Scoreboard can't be closed

### ISSUE THREAD

**Issue by kmy981** [SDLash3D/cs16-client#147]
I have an issue where one scoreboard shows by default and won't close.

This is the scoreboard that can be opened and close.
![screenshot_2016-04-18-15-12-07 1](https://cloud.githubusercontent.com/assets/18525448/14596301/10afe0b8-0578-11e6-8725-9af018eed43b.jpg)

And this is the one that opens automatically and is stuck there as soon as I load into a game.
![screenshot_2016-04-18-15-11-55 1](https://cloud.githubusercontent.com/assets/18525448/14596304/16190dfe-0578-11e6-9982-99f6ddbc722a.jpg)

**Comment by a1batross** [comment]
x86-related bug. Already fixed.
