### ISSUE TITLE
Лишние звуки в игре

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#15]
При сворачивании и развороте игры воспроизводится звук воды, будто я из неё выплыл. Зато забавно.
Такое чувство, как будто звуки шагов и иногда выстрелов воспроизводятся на несколько раз одновременно, когда идёшь, такое чувство что еще кто то идёт рядом, при том что я один.

**Comment by sergiopoverony** [comment]
Звук воды всегда был, при подвисании игры или пролох коннекте.

**Comment by mittorn** [comment]
Шаги относятся и к хл

**Comment by sergiopoverony** [comment]
Со звуком еще надо что то делать. Потому что в наушниках сидиш... человек бежит с лева... а звук его шагов с права... и потом когда игрок становится в зоне видимости с левой части  шаги меняют уровень громкости и становятся правильно слева- откуда и появился враг. Слышны звуки закупки и звук кнопки USE на всю карту. Т.е. враг закупается или жмет кнопку Use  на другом краю карты - я его слышу.
