### ISSUE TITLE
Разминирование

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#16]
После переключения наблюдения на человека, минирующего бомбу, полоска не синхронизируется. После разминирования она продолжает заполняться. (скриншот не приложу, т.к. не успел).
Сергей Ларин cerg2010cerg2010

**Comment by sergiopoverony** [comment]
Бомбу можно разменировать закрывшись щитом. Так не должно - разминирование только при открытом щите.

**Comment by ahsim** [comment]
Если вы играете за террористов и у вас есть бомба, то при попадании на любой из плентов зеленый значок бомбы начнет мигать красным. Здесь же данный эффект отсуствует.
bull24 (4PDA), или KitKat (Skype).

**Comment by sergiopoverony** [comment]
При установке бомбы, время  (игровой таймер) должне сменяться на таймер обратного отчета бомбы. Т.е. показывать после установки  0,45 и идти к нулю 0,00 - потом взрыв. Таймер не меняется, а дальше показывается время раунда...

**Comment by a1batross** [comment]
#37

Так как то, что написано в самом багрепорте -- исправлено, эту  закрою, а ту оставлю.
