### ISSUE TITLE
CS16Client v1.01

### ISSUE THREAD

**Issue by D1N13** [SDLash3D/cs16-client#161]
I not have button "buy". Can't any bought. 
And, I not understand. What I must do with this folder "CS16Client v1.01"?. 
All that inside add to "cstrike"?

**Comment by nekonomicon** [comment]
>I not have button "buy". Can't any bought.

Configuration->touch->touch options->profiles.

>What I must do with this folder "CS16Client v1.01"?

Nothing. Remove it. It for coders only.

**Comment by D1N13** [comment]
Thank you!
