### ISSUE TITLE
3D side-by-side

### ISSUE THREAD

**Issue by bambus1980** [SDLash3D/cs16-client#166]
Waiting for Cardboard compatibility!
Main thing to play old games in 3D VR!
How difficult to split display out into double windows? Simple dublicate same picture into two windows.

**Comment by Solexid** [comment]
VR mode will be added next week.Stay tuned

**Comment by bambus1980** [comment]
is it realized vr-mode?

**Comment by a1batross** [comment]
It will be released after release of Xash3D SDL on Google Play. Maybe in the same day.

But even I don't know when Xash3D SDL will be posted on GP. (licensing issues)
