### ISSUE TITLE
Unable to find installation folder

### ISSUE THREAD

**Issue by dilip-md** [SDLash3D/cs16-client#167]
I am using Nexus 5 and I am  unable to find the installed folder of both cs 1.6 and xash... I am using ES file explorer..... Both the folder are not shown .... Where do I find them.....?

**Comment by Francefire** [comment]
You must create xash folder in /sdcard/ (depend on devices) your cs1.6 must come from your computer, just copy the cstrike and valve folder in cash folder

**Comment by Francefire** [comment]
Xash* not cash ;)
