### ISSUE TITLE
Худ

### ISSUE THREAD

**Issue by Zu1iNMage** [SDLash3D/cs16-client#185]
При подъеме или закупе aug'а или krieg 552 иконка в худе артефактная. Коли речь про худ сразу скажу, что старый баг с исчезновением каски с картинки армора снова появился - закупаем кевлар с каской, жмем на чат, после чего у нас исчезнет каска.

**Comment by a1batross** [comment]
Не смог воспроизвести баг с AUG/Krieg.

**Comment by a1batross** [comment]
Каска исчезает так как происходит реинициализация HUD, так как меняется размер окна.
