### ISSUE TITLE
Звук

### ISSUE THREAD

**Issue by RomkaZVO** [SDLash3D/cs16-client#19]
Играя на сервере 1 на 1 обнаружил баг звука,прекрасно слышен звук закупа у Т(я играл за КТ).
И слышны шаги,как будто рядом,но Т находился ещё на респе и никаких шагов ещё не должно быть.

**Comment by sergiopoverony** [comment]
Это походу какоето дублирование. Заметил, что когда на сервере никого нету, и ты бегаешь... шаги становятся с небольшим эхом... будто я слышу шаги на стороне клиента, но еще и сервер передает мне мои шаги.

**Comment by RomkaZVO** [comment]
Кст,я тоже обратил на это внимание

**Comment by a1batross** [comment]
Это из-за предикта.

**Comment by GFOXSH** [comment]
Кстати, в Xash3D та же история. Отметил, что эффект появляется после загрузки карт (четных от  начала, т.е. 2, 4, 6 и т. д.).

**Comment by a1batross** [comment]
https://github.com/SDLash3D/cs16-client/issues/15

Тот же баг.

**Comment by valera0141** [comment]
Играя на серве меня вдруг выкинуло. При обратном входе моё количество денег сохранилось, а должно сбросится.

**Comment by valera0141** [comment]
При падении с высоты в воду (воды поколено игроку) воспроизводится звук удара о землю из хл,  а не из кс.

**Comment by a1batross** [comment]
Заведи отдельную иссусю. В закрытых я никогда не смогу это исправить.
