### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Kraxeeer** [SDLash3D/cs16-client#2]
Commands are working good.
I started lan game and try to write "jointeam 1" - i got uncown command error... With joinclass 1 and any other servers for , not game engine it's not working. Command "gail" or "deagle" etc are not work too -.- What The Fu*k? On your video all work okay. :( metamod/amx/podbot are not working too :O ;..; xash3D+cs1.6 client+1.6 v48 steam files.

**Comment by a1batross** [comment]
You are trying to play on Linux version of Xash3D SDL or Android? 

Menu works like in an old versions of CS. Just bind numbers to slots(bind 1 slot1, etc).
Buy menu opens through buy command.

**Comment by sergiopoverony** [comment]
i play on cs1.6 client+1.6 v48 steam files - buymenu work ok. No hud )

**Comment by Kraxeeer** [comment]
Android version. If i write buy in console i got "uncown command".

**Comment by Kraxeeer** [comment]
It's not work! I do clean install on pc, copied all game files to  and unpacked client.dll port to cstrike folder. Game work ok but anyway i can't use commands -.;

**Comment by a1batross** [comment]
Hah. Android can't load libraries from sdcard or another places. You must build an APK with libclient.so only and run it. 

It in a beta testing, so I suggest you waiting until official release.

**Comment by Kraxeeer** [comment]
Yyyy what?. If it's moment please do this for me. Btw. Arm linux can run it?

**Comment by a1batross** [comment]
Yes. ARM Linux is works.

**Comment by ayushhj79** [comment]
Plz provide me link for cs1.6 apk..
