### ISSUE TITLE
Энтити

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#21]
Не все энтити работают правильно. На карте естате  - типа меншена, с зади дома стоит электрощиток - которым выключается свет во всем доме... темную устраивать. Щиток переключается а свет как горел, так и горит.
В консоли высыпает такое... 

![screenshot_2015-11-10-22-28-40](https://cloud.githubusercontent.com/assets/5286127/11070044/3cf7831a-87fb-11e5-9a11-ed1cf9cf048d.png)

**Comment by a1batross** [comment]
Он не горит у лестниц, на части второго этажа. С этим всё в порядке. 
(В Steam CS1.6 так же)
