### ISSUE TITLE
Заложники

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#22]
При наведении прицела на заложника,  вне зависимости от того, за какую ты команду - показывается их жизнь в процентах.. к примеру 100% при стрельбе и попадании в заложников, проценты отнимаются... 
--- СЕЙЧАС - в игре ничего такого не отображается.  После убийства должно отображаться -Вы убили заложника. + в зависимости от настроек. Обычно по дефолту после убийства 5 залогов - кикало с сервера )))

**Comment by mittorn** [comment]
HostageK не реализован пока что

**Comment by sergiopoverony** [comment]
Пофикшено
