### ISSUE TITLE
Консольные сообщения

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#23]
Часто вываливаеются такие сообщения, при коннекте к серверу. 
![screenshot_2015-11-10-19-12-24](https://cloud.githubusercontent.com/assets/5286127/11070075/6d6621e6-87fb-11e5-9a9b-60b4c25059a5.png)

**Comment by mittorn** [comment]
Это нормально. Эти сообщения ещё не реализованы.
Их надо дописывать
