### ISSUE TITLE
Вид от камеры / Наблюдатель

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#25]
После захода на сервер за наблюдателя. Можно переключаться между игроками и смотреть по сторонам, клацать кнопки... при нажатии кнопки стрельбы - иногда проскакивает полоска разминирования бомбы.

**Comment by mittorn** [comment]
так же при повторном подключении прогрессбар не чистится.

**Comment by RomkaZVO** [comment]
Когда тебя убивают, когда вращаешь камерой от 3го лица,то труп некоторое время крутиться

**Comment by mittorn** [comment]
Это баг сервера, который valve пытаются исправить в клиенте. Если это убрать, камера не будет крутиться.

**Comment by a1batross** [comment]
Баг с прогрессбаром уже исправлен.
