### ISSUE TITLE
Error:loading library /data/data/in.celest.xash3d.cs16client/lib/libserver_hardfp.so 

### ISSUE THREAD

**Issue by ridvan1995** [SDLash3D/cs16-client#32]
I compiled and installed on my phone but can't opening.
![screenshot_2015-11-16-20-49-47 1](https://cloud.githubusercontent.com/assets/11977128/11191414/d1df249a-8ca3-11e5-8f81-3297f571aa49.png)

**Comment by ridvan1995** [comment]
Note: My phone os is Android 4.4.2

**Comment by a1batross** [comment]
Congratulations! 

You are automatically in half-closed beta test now. You may join to the servers in Internet games. Or set up server on your computer in local network.
Creating native servers is not working on Android.

**Comment by ridvan1995** [comment]
its connect the original Counter-Strike 1.6 client.dll servers?

**Comment by a1batross** [comment]
Not entirely. 

Server must be started with Xash3D. But game code is original. (mp.dll, cs.so works with Xash3D)
