### ISSUE TITLE
Надписи title.txt

### ISSUE THREAD

**Issue by lewa-j** [SDLash3D/cs16-client#33]
Во многих местах вместо текста надписи отображается что-то вроде: "Cstrike_TitlesTXT_Switch_To_BurstFire"

**Comment by a1batross** [comment]
Потому что нужно сконвертировать resources/cstrike_english.txt из UTF16 в UTF8. 

Пока не знаю как грамотно решить это. Или не париться и сунуть подобное в экстрас(который в итоге никто не будет трогать), или в коде сделать отдельный парсер для UTF16.

**Comment by GFOXSH** [comment]
Лучше в коде сделать отдельный парсер для UTF16. Ибо extras зачастую просто игнорируют.
