### ISSUE TITLE
Не доработка сервера

### ISSUE THREAD

**Issue by valera0141** [SDLash3D/cs16-client#35]
Играя на серве меня вдруг выкинуло. При обратном входе моё количество денег сохранилось, а должно сбросится. Если я спектатор и нажму на прыжок, то кнопки становятся белыми.

**Comment by a1batross** [comment]
Первое не баг. Это движок так работает. 

А про последнее, можешь показать? Или видео записать.

**Comment by valera0141** [comment]
Ок,  потос скрин сделаю. Игроков надо
