### ISSUE TITLE
Указатель бомбы

### ISSUE THREAD

**Issue by GFOXSH** [SDLash3D/cs16-client#37]
После установки бомбы зеленый указатель должен мигать красным у всех игроков, указывая как скоро она взорвется. Но вместо этого просто исчезает.
![screenshot_2015-11-22-13-17-01](https://cloud.githubusercontent.com/assets/15711761/11323638/41202fba-9128-11e5-8eaf-8616b8a29b67.png)

И та же проблема с обратным отсчетом.

**Comment by a1batross** [comment]
Проверил на стиме. Ничего подобного. Да, статус иконка мигает у игрока с бомбой в зоне, это будет исравлено, но после плента у всех остальных максимум -- исчезает таймер.
