### ISSUE TITLE
Стрельба. 

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#4]
1. При выстреле, первый выстрел - происходит звук выстрела и спрайт огня из ствола на пистолетах. Последующие выстрелы без визуально/звуковых эффектов. На автоматах - рандомно

2. Крестовина прицела из HL/ в кС другая... с динамикой при отключении в настройках crosshair 0 - то прицела нету ни на одном оружии. 

3. Прицел самопроизвольно исчезает и появляется когда покупаются полуснайперки (aug,552)

**Comment by MakcuM56** [comment]
1. cl_lw и cl_lc нужно выставить на 0 в config.cfg - тогда будет работать анимация выстрелов.

**Comment by GFOXSH** [comment]
Кстати, странный баг: после выстрела анимация может повторятся до бесконечности долго, без звука и урона.

**Comment by a1batross** [comment]
Исправлено.
