### ISSUE TITLE
Баг с заложниками

### ISSUE THREAD

**Issue by GFOXSH** [SDLash3D/cs16-client#40]
Можно вести за собой не более 3 заложников. Причина неизвестна.

**Comment by a1batross** [comment]
Перед тем как отослать баг, попробуйте раза три его воспроизвести. 

У меня с первого раза все заложники добежали. И это на тормозном XashDS/QEMU

**Comment by GFOXSH** [comment]
Верно, попробовал их подтолкнуть - пошли.
