### ISSUE TITLE
Проблема запуска на некоторых устройствах

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#43]
Здесь будет информацию от игроков у которых не удалось запустить игру:
- Аппарат - Alcatel OneTouch Idol 2 6037Y
проц. MT6582, граф.ускоритель Mali-400MP
[engine(3).log.txt](https://github.com/SDLash3D/cs16-client/files/43866/engine.3.log.txt)
Проблема - открываю лаунчер кс, жму запустить, захожу в игру в выходит это
![63b79c16c515646a5c18191dbc76076f795182bc2e20418a46 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/10883357/11398254/289706f0-9388-11e5-9ef0-7dd0db1f6f8b.jpg)
Тестер - Cергей Павлов (snake11542)

**Comment by ahsim** [comment]
2. Аппарат - Xiaomi Mipad
Nvidia Tegra K1
[engine.log.txt](https://github.com/SDLash3D/cs16-client/files/43903/engine.log.txt)

**Comment by GFOXSH** [comment]
У меня тоже такое было. Но после непродолжительного ожидания CS1.6 все таки запускался с сервером из-под XashDS. ImPad 4313, Cortex-A7, Mali-400MP.

**Comment by ahsim** [comment]
- Аппарат Lenovo A2010 Не возможно запустить 
[engine(3).log.txt](https://github.com/SDLash3D/cs16-client/files/46408/engine.3.log.txt)
Тестер Se Android 2.2

**Comment by ZyX3L** [comment]
Can i join beta testing? i have lots of devices to test it on

**Comment by a1batross** [comment]
@ZyX3L
No.

You may download our "demo"-version. But you will not receive any tech
support and any reports will be ignored.

http://www.moddb.com/games/xash3d-android/downloads/cs16-client-first-public-version-unsupported

2016-02-01 14:35 GMT+06:00 ZyX3L <notifications@github.com>:

**Comment by ZyX3L** [comment]
Okay :) But Where Can I Find This "Demo" Version?

**Comment by ZyX3L** [comment]
Nevermind Thanks :D

**Comment by ZyX3L** [comment]
I Really Dont Want To Interrupt You But I Dont Have A Cstrike Folder In The "Xash" Folder Please Help :(

**Comment by ahsim** [comment]
более менее проблема решена, да и нехрен держать такую ишую открытой. По каждой индивидуальной проблеме будет создана своя ишуя. Закрываю
