### ISSUE TITLE
Бомба и время раунда

### ISSUE THREAD

**Issue by Mars873** [SDLash3D/cs16-client#45]
КТ выигрывают по истечении времени, даже если бомба поставлена.

**Comment by GFOXSH** [comment]
И невозможно определить, у которого из террористов бомба.

![screenshot_2015-11-28-15-20-50](https://cloud.githubusercontent.com/assets/15711761/11451846/cedcbe84-95e4-11e5-8965-df04e6e707af.png)

**Comment by GFOXSH** [comment]
Аналогично с наборами сапера:

![screenshot_2015-11-28-15-40-20](https://cloud.githubusercontent.com/assets/15711761/11451922/e99d68d4-95e6-11e5-8601-c28c9ef1f72d.png)

**Comment by a1batross** [comment]
Попробовал воспроизвести. Ничего подобного.
