### ISSUE TITLE
Динамический прицел

### ISSUE THREAD

**Issue by RomkaZVO** [SDLash3D/cs16-client#46]
Прицел ведёт себя неадекватно:
1) При приседания он сначала расширяется,а только потом сжимается, а должен сразу.
2)При ходьбе прицел не увеличивается, только при прыжке и хождении по ступенькам.

**Comment by sergiopoverony** [comment]
Все верно сейчас. Обнули у себя на контре конфиги. и увидешь - что работают они также.

**Comment by GFOXSH** [comment]
Подтверждаю, прицел работает нормально.
