### ISSUE TITLE
Настройки прицела.

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#47]
cl_crosshair_translucent 0/1 не работают должным образом. При команде 0 - прицел не должен быть полупрозрачным, просто прицел без прозрачности должен быть. Сейчас он просто исчезает. Соответвенно, чтобы сделать черный прицел через команду cl_crosshair_color "1 1 1" - он становится невидимым.

**Comment by ahsim** [comment]
не работает изменение размера прицела cl_crosshair_size
Всегда одинаковый при любых значениях small/medium/large
Но с разным оружием - разный размер прицела.

**Comment by a1batross** [comment]
Я подозреваю, что он исчезает из-за Blend бага в GLES. 

Попробую пофиксить это не сменой рисующей функции, а просто делая его совсем непрозрачным.
Сейчас используется такой же вариант, который и в оригинале.
