### ISSUE TITLE
Переключение оружия

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#48]
После обновления от 28-29,11,2015 появился баг при переключении оружия, если на пистолете кончились патроны и ты переключился на нож, то обратно на пистолет переключится нельзя, соответственно его и выкинуть нельзя, чтобы подобрать с земли другой.

**Comment by ahsim** [comment]
ну и с автоматами также

**Comment by GFOXSH** [comment]
Также не работает автовыбор наиболее мощного оружия.

**Comment by sergiopoverony** [comment]
Пофикшено
