### ISSUE TITLE
Декали от пуль

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#49]
Нет чужих декалей. 

// поменял описание, -- a1batross.

**Comment by sergiopoverony** [comment]
При стрельбе в стену, я не вижу чужие декали - только свои. Стреляли в одну стену с Мишей

**Comment by GFOXSH** [comment]
Играю с ботами. Чужие декали то есть, то нет.

**Comment by a1batross** [comment]
Пофикшено. 
Бага была в движке, как оказалось. Такой же баг присутствовал в HL1.
