### ISSUE TITLE
reconnect 

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#5]
Команда reconnect  - крашит приложение. Пробовал разными способавми. Вылет приложения. (Кто тописал что у них нормально, возможно зависит от девайса.)

**Comment by Messi9401** [comment]
Подтверждаю, такая проблема есть, но у меня крашится не сразу. Может закрашиться только если реконектиться несколько раз.

**Comment by GFOXSH** [comment]
Команда reconnect крашит приложение в LAN сети. Пробовал OOM -17 - дает сделать один reconnect, при втором опять крашит.

**Comment by sergiopoverony** [comment]
Пофикшено
