### ISSUE TITLE
Лагающий прицел на AWP и AUG/Krieg

### ISSUE THREAD

**Issue by cerg2010cerg2010** [SDLash3D/cs16-client#52]
На AWP при приближении появляется сначала бОльший прицел, потом меньший. Да и приближается как то странно, мелькает экран) После выхода из зума ходишь медленно. Исправляется переключением оружия. На AUG из зума вообще нельзя выйти + в нем нет прицела.

**Comment by a1batross** [comment]
Скажи, это с включенным cl_lw или без?

**Comment by cerg2010cerg2010** [comment]
С включенным.

**Comment by a1batross** [comment]
Тогда это норма. :)

Клиентское оружие пока недоделано особо. Но с ним уже круто играть. 

Тут ещё накладывается то, что движок плюёт на FOV. Потому с прицелом такая байда.

**Comment by a1batross** [comment]
Исправлено в движке.
