### ISSUE TITLE
Отсутвуют важные декали

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#54]
Отсутвуют важные декали в местах укладки бомбы/зонах спасения. Никто не обратил внимания на данный факт, так как часто зоны спасения заложников или закладки бомбы помечены крестиком (текстурно). Но на некоторых картах - это тоже помечено текстурно, но Декалиями. На примере карты cs_siege. Декали на карте присутствуют, в комнате с заложниками, кровь на стенах(декали) присутвуют.
2 скрина. Один где есть дикали - из Стима, где нету из Нас ) 
![cs_siege0000](https://cloud.githubusercontent.com/assets/5286127/11521335/230abb60-98cd-11e5-9185-ca1e2c38c2ce.jpg)
![screenshot_2015-12-02-08-08-34](https://cloud.githubusercontent.com/assets/5286127/11521352/4c0221f2-98cd-11e5-8ee4-c27f42ccaa95.png)

**Comment by a1batross** [comment]
Интересно то, что они рандомно появляются и так же рандомно исчезают. Особоенно на новый раунд.


Хотя я кажется в курсе. На каждый новый раунд вызывается ивент decal_reset.sc. Вот походу их надо аккуратнее чистить. :)

**Comment by sergiopoverony** [comment]
Кстати на ноже прицел есть )

**Comment by a1batross** [comment]
Пофикшено в движке. R_RemoveDecalAll в ГС не удалял BSP декали, а здесь сносил.
