### ISSUE TITLE
СМЕНА КАРТЫ, игроки, подключение игроков, время карты

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#57]
При смене карты сервером. Показывается таблица счета и игроков. Игроки должны замирать. На данный момент замирает только вращение камерой. Если смена карты произошла во время игры, при стрельбе - то можно бегать и стрелять. Передвижения игрока не блокируется, блокируется только камера. Должно блокироваться как передвижение так и повороты камерой.

**Comment by sergiopoverony** [comment]
Причем можно стрелять скрытым оружием.

**Comment by sergiopoverony** [comment]
Когда меняется карта... появляется скореборд. Должен произойти реконнект к серверу - но он не происходит... пока не нажмешь стрелять.

**Comment by sergiopoverony** [comment]
Я ПОДКЛЮЧАЮСЬ К СЕРВЕРУ: Я подключаюсь к серверу, а на сервер должна была сменится карта. Выглядит это вот так, бывает оружие в руках есть, бывает его нет.
Если нажать "Стрелять" то происходит рекконнект и смена карты на сервере. 
![screenshot_2016-01-12-08-25-00](https://cloud.githubusercontent.com/assets/5286127/12254086/ec21a834-b906-11e5-9f51-3b8d37d7035b.png)

**Comment by sergiopoverony** [comment]
СМЕНА КАРТ НА СЕРВЕРЕ: Смена карт на сервере должна осуществляться автоматически по таймеру (команде mp_timelimit ) Данное время должно идти в не зависимости есть игроки на сервре или нет. 
СЕЙЧАС: сейчас время считается только когда игроки играют на сервере. Если игроков нет, то карта весит всегда. 
ДОЛЖНО: Время должно идти в не зависимости есть игроки на сервере или нет, чтобы карты сами менялись.

**Comment by a1batross** [comment]
Это не проблемы клиента. 

И да, я один не вижу ничего общего между всеми этими комментариями?
