### ISSUE TITLE
Сторонние повреждения игроку и вибрация

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#60]
В игре предусмотрены еще несколько видов повреждений. Заморозка - отображается снежинка на экране, радиация - отображается значок радиации, огонь - отображается костер (Также при смерти от С4 взрыва). На основе этих данных можно определить тип вибрации.

**Comment by sergiopoverony** [comment]
Косяк у вальве с отображением значков. 
![qip shot - screen 519](https://cloud.githubusercontent.com/assets/5286127/11611941/d0b5f45a-9c06-11e5-85a2-bbd83d5096b8.png)
Вот все виды значков повреждений. И в КС они не правильные. Вместо снежинки - отображается противогаз, вместо кислорода 02 - показывает снежинку.

**Comment by sergiopoverony** [comment]
Нужно в меню регулировку силы выбрации с проверкой

**Comment by a1batross** [comment]
Done.
