### ISSUE TITLE
CS16-Client Windows Compatibility

### ISSUE THREAD

**Issue by ridvan1995** [SDLash3D/cs16-client#62]
Please add the source code Windows compatibility

cl_dll log
[cl_dll.txt](https://github.com/SDLash3D/cs16-client/files/72178/cl_dll.txt)

mainui log
[mainui.txt](https://github.com/SDLash3D/cs16-client/files/72180/mainui.txt)

mp log
[mp.txt](https://github.com/SDLash3D/cs16-client/files/72181/mp.txt)

**Comment by a1batross** [comment]
Nope. 
You can run CS1.3 client with 1.6 server on Xash3D.
