### ISSUE TITLE
Yapb is not working

### ISSUE THREAD

**Issue by steadyfield** [SDLash3D/cs16-client#70]
I Checked the CheckBox "Use CS16nd Server" and launched the game. After loading a map, I entered "yb_version" in the console. It said "Unknown command yb_version". The libyapb.so file exists in the directory "/data/data/in.celest.xash3d.cs16client/lib".

**Comment by a1batross** [comment]
I don't give any support(except for beta testers). 

Please, wait until full release.

**Comment by steadyfield** [comment]
@a1batross ok, sorry for bothering. I will never post anything there from now.
