### ISSUE TITLE
Incorrect bot name

### ISSUE THREAD

**Issue by leopard20** [SDLash3D/cs16-client#71]
I have been playing CS my whole life. Such bots don't exist.
Note that bot names and difficulty are contained in a file named botprofile.db. You can open it using notepad.
![952fbf14-b3f9-11e5-9759-486b627f6c09](https://cloud.githubusercontent.com/assets/16115820/12146386/9de72138-b4a8-11e5-967c-6135e45e2b21.png)

**Comment by lewa-j** [comment]
These names are changed tester itself.

**Comment by sergiopoverony** [comment]
I use YaPB bots in game, BOT prefix i write specially

**Comment by leopard20** [comment]
What is yapb? Does it support difficulty for bots?
