### ISSUE TITLE
ОРУЖЕЙНЫЕ БАГИ

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#73]
Анимация USP поломана
![screenshot_2016-01-23-14-10-21](https://cloud.githubusercontent.com/assets/5286127/12529546/bc539660-c1dc-11e5-92a4-a94ec3d88f5e.png)

**Comment by sergiopoverony** [comment]
Аналогично происходит с glock - также бывает анимация съедена. 

Снайперская винтовка SCOUT - при выстреле. Делакль от выстрела появляется не на стене а на потолка с права от игрока. 

Дробовики - нету разброса декалий. Просто будто одной пулькой стреляет. 
![screenshot_2016-01-11-22-11-47](https://cloud.githubusercontent.com/assets/5286127/12241252/fd84f02a-b8b3-11e5-9262-c3b2b8c808d5.png)

**Comment by sergiopoverony** [comment]
Не понятно работает BURST мод у фамаса и глока. Должна анимация быть будто 3 пули вылетает. Анимация как будто вылетает одна пуля.

**Comment by GFOXSH** [comment]
Перепутаны звуки с глушителем и без у основного пистолета CT.

**Comment by sergiopoverony** [comment]
Чего не читаешь - написано выше.

**Comment by artslay** [comment]
Баг с анимацией у дробовика Leone 12

При зажатии кнопки огонь, после третьего выстрела, появляется анимация перезарядки.

Если нет патронов, и зажать огонь, звук зацикливается в ускоренном режиме.

**Comment by artslay** [comment]
Баг с автоматическим дробовиком.

При перезарядке, если зажать огонь - проигрывается звук перезарядки, но выстрела нет.

**Comment by Zu1iNMage** [comment]
Ну так то burst у глока в оригинале как раз таки словно одной пулей выстреливает
