### ISSUE TITLE
RE-Buy 

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#75]
Не работает re-buy
Auto-buy срабатывает как надо. При изменении autobuy.txt  все нормально - покупается нужно
RE-Buy - отсылает набор, команды в консоли, но ничего не покупается
![screenshot_2016-01-11-10-47-00](https://cloud.githubusercontent.com/assets/5286127/12227625/410598b2-b851-11e5-85a3-eb79477e42f4.png)

**Comment by a1batross** [comment]
Напомни, ты это тестил на cs16nd или на оригинале?

**Comment by sergiopoverony** [comment]
Тестировал на твоем.
