### ISSUE TITLE
Время покупки (отображение информации)

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#76]
Не корректно отображается информации об окончании времени закупки оружия. 
Вместо 901 должно отображаться время, которые дается на закупку... 
типа 15 second has passed. 
![screenshot_2016-01-11-21-53-05](https://cloud.githubusercontent.com/assets/5286127/12240281/60327dd8-b8ae-11e5-98c5-0d5e7ca855cc.png)

**Comment by a1batross** [comment]
Не 901, а 90. Ненужный символ попадает.
