### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#81]
Не хватает общего счета для комманд а также и latency, т.е. пинг. 
Пока есть только для каждого поотдельности
Вот как должно выглядеть:
![iebl1oo5s-m](https://cloud.githubusercontent.com/assets/10883357/12376805/e7ab366a-bd0e-11e5-92e8-8a3d78d15212.jpg)

Также имя смещается во время подключения новых игроков:
![1kul-dq7-jc](https://cloud.githubusercontent.com/assets/10883357/12376810/0fc21f74-bd0f-11e5-9f98-60af6a449e82.jpg)

**Comment by a1batross** [comment]
https://github.com/SDLash3D/cs16-client/commit/2e127dd1ec3f4bf60dee047392cfc3ac70a66f5a
