### ISSUE TITLE
Меню в игре

### ISSUE THREAD

**Issue by ahsim** [SDLash3D/cs16-client#82]
Есть замечательные команды
_vgui_menus "1"
_extended_menus "1"
которые надо было бы реализовать как нибудь в меню. Будь то в лаунчере либо в самой игре (лучше в игре).

**Comment by ahsim** [comment]
есть возможность отключить в тачевом меню. Так что можешь закрыть пока эту ишую

**Comment by a1batross** [comment]
По-хорошему, он в mainui должен быть. 

Я конечно "за" эти ваши тачевые меню, ибо работу сильно облегчает, но... Оно работает только с тачем.

**Comment by a1batross** [comment]
mainui давненько уже дополнен всяким. Закрываю.
