### ISSUE TITLE
РАДАР - размер точек на радаре.

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#88]
Нужно увеличить всю отображаемую информацию на радаре. Все точки. Т.к. на маленьком экране ничего не видно вообще. 
![screenshot_2016-01-25-16-36-14](https://cloud.githubusercontent.com/assets/5286127/12549853/e348cffa-c381-11e5-8670-4131a14c78e4.png)
Вот так выглядят у нас точки игроков (нам надо побольше)

**Comment by a1batross** [comment]
Закинул бы про T в отдельную ишшую.
