### ISSUE TITLE
Гранаты 

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#9]
Все гранаты нормально, кроме как - Дымовая граната у меня не работает.. вместо дыма - спрайты какето бразгают из нее. Дыма нет (возможно зависит от девайса)

**Comment by RomkaZVO** [comment]
Дым работает (N7 2013)

**Comment by GFOXSH** [comment]
ImPAD 4313 - дым работает. Правда, FPS сильно проседает.

**Comment by a1batross** [comment]
@RomkaZVO @GFOXSH А можете скрины показать? Просто у меня самого не работают, ни на ПК, ни на андроиде. 
Вот и поставил как замену партикли.

**Comment by a1batross** [comment]
Дым есть, но только на один раз. 
Дальше движок снова ругается на прекеш.


Valve, неужели так сложно было прекешировать ещё gas_puff_01.spr? >_<

**Comment by sergiopoverony** [comment]
Ждем исправление

**Comment by THE-Swank** [comment]
У меня вообще не какого дима нет.
