### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by leopard20** [SDLash3D/cs16-client#91]
The radar should be transparent, not opaque (as it is right now).

**Comment by sergiopoverony** [comment]
This no bag. This is you - dont know Counter Strike
cl_radartype 1 - no opaque
cl_radartype 0 - opaque


CLOSED

**Comment by a1batross** [comment]
As I said you, there is no tech support, except beta testers. Just go away, you will be notified after first release.

**Comment by leopard20** [comment]
Why the hell are you rude? I'm just trying to help.

**Comment by a1batross** [comment]
@leopard20 
I am sorry for being rude. 
But we don't need help. 

If you want to contribute, you  may look into opened issues in engine or android project.
