### ISSUE TITLE
РАДАР - отображение на радаре

### ISSUE THREAD

**Issue by sergiopoverony** [SDLash3D/cs16-client#99]
Радар - после смены карты иногда отображаются точки - иногда вообще ничего не показывает

![screenshot_2016-02-04-21-14-13](https://cloud.githubusercontent.com/assets/5286127/12822843/ad1c462a-cb8b-11e5-855f-5a51f8af079c.png)
![screenshot_2016-02-04-21-19-34](https://cloud.githubusercontent.com/assets/5286127/12822842/ad192f76-cb8b-11e5-90c5-1d7a09727bb8.png)

**Comment by a1batross** [comment]
Первый скрин бесценный. Особенно, чат. 

Я все ещё не пойму где надо чистить структуры игроков.

**Comment by a1batross** [comment]
Баг я пофиксил. Но не уверен, что полностью. 

Тут кстати вполне возможно, что это сетевые проблемы. Локально воспроизвести тоже так и не удалось.
